"""add_is_protected_to_lineage_event

Revision ID: 36e7d6258a25
Revises: efc94c85dbe0
Create Date: 2025-12-22 18:51:07.159214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e7d6258a25'
down_revision: Union[str, None] = 'efc94c85dbe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply database schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lineage_event', sa.Column('is_protected', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert database schema changes.
    
    WARNING: Make sure this migration is reversible!
    Consider data loss implications before rolling back.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lineage_event', 'is_protected')
    # ### end Alembic commands ###
