"""add_wikipedia_summary_to_team_node

Revision ID: 71801b75caaa
Revises: 4f7041e3cad0
Create Date: 2026-01-08 09:20:45.836264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71801b75caaa'
down_revision: Union[str, None] = '4f7041e3cad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply database schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_node', sa.Column('wikipedia_summary', sa.Text(), nullable=True, comment='Concatenated Wikipedia history from all languages for lineage analysis'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert database schema changes.
    
    WARNING: Make sure this migration is reversible!
    Consider data loss implications before rolling back.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_node', 'wikipedia_summary')
    # ### end Alembic commands ###
