"""add precomputed_layouts table

Revision ID: 990f5be30082
Revises: f3a1b2c3d4e5
Create Date: 2026-01-28 20:04:58.266108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.db.types

# revision identifiers, used by Alembic.
revision: str = '990f5be30082'
down_revision: Union[str, None] = 'f3a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply database schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precomputed_layouts',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('family_hash', sa.String(length=64), nullable=False),
    sa.Column('layout_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('data_fingerprint', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('optimized_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_family_hash', 'precomputed_layouts', ['family_hash'], unique=True)
    op.create_index('idx_optimized_at', 'precomputed_layouts', ['optimized_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert database schema changes.
    
    WARNING: Make sure this migration is reversible!
    Consider data loss implications before rolling back.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_optimized_at', table_name='precomputed_layouts')
    op.drop_index('idx_family_hash', table_name='precomputed_layouts')
    op.drop_table('precomputed_layouts')
    # ### end Alembic commands ###
