"""Add country_code to team_era

Revision ID: d0d769119ce5
Revises: 001_initial
Create Date: 2025-12-18 11:41:44.774440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0d769119ce5'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply database schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('edit_history', 'action',
               existing_type=postgresql.ENUM('CREATE', 'UPDATE', 'DELETE', name='edit_action_enum'),
               type_=sa.Enum('CREATE', 'UPDATE', 'DELETE', name='editaction', native_enum=False),
               existing_nullable=False)
    op.alter_column('edit_history', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'APPLIED', name='edit_status_enum'),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'APPLIED', name='editstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::edit_status_enum"))
    op.alter_column('edit_history', 'snapshot_before',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('edit_history', 'snapshot_after',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.drop_index('idx_edit_history_entity', table_name='edit_history')
    op.drop_index('idx_edit_history_status', table_name='edit_history')
    op.drop_index('idx_edit_history_user_id', table_name='edit_history')
    op.alter_column('lineage_event', 'event_type',
               existing_type=postgresql.ENUM('LEGAL_TRANSFER', 'SPIRITUAL_SUCCESSION', 'MERGE', 'SPLIT', name='lineage_event_type_enum'),
               type_=sa.Enum('LEGAL_TRANSFER', 'SPIRITUAL_SUCCESSION', 'MERGE', 'SPLIT', name='event_type_enum', native_enum=False),
               existing_nullable=False)
    op.drop_index('idx_lineage_event_predecessor', table_name='lineage_event')
    op.drop_index('idx_lineage_event_successor', table_name='lineage_event')
    op.drop_index('idx_lineage_event_type', table_name='lineage_event')
    op.drop_index('idx_lineage_event_year', table_name='lineage_event')
    op.drop_index('idx_sponsor_brand_master_id', table_name='sponsor_brand')
    op.drop_index('idx_sponsor_master_legal_name', table_name='sponsor_master')
    op.drop_index('idx_sponsor_master_protected', table_name='sponsor_master')
    op.add_column('team_era', sa.Column('country_code', sa.String(length=3), nullable=True))
    op.drop_index('idx_team_era_node_id', table_name='team_era')
    op.drop_index('idx_team_era_season_year', table_name='team_era')
    op.drop_index('idx_team_era_tier_level', table_name='team_era')
    op.drop_index('idx_team_node_dissolution_year', table_name='team_node')
    op.drop_index('idx_team_node_founding_year', table_name='team_node')
    op.drop_index('idx_team_node_is_active', table_name='team_node')
    op.drop_index('idx_team_node_legal_name', table_name='team_node')
    op.drop_index('idx_team_sponsor_link_brand_id', table_name='team_sponsor_link')
    op.drop_index('idx_team_sponsor_link_era_id', table_name='team_sponsor_link')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('EDITOR', 'TRUSTED_EDITOR', 'MODERATOR', 'ADMIN', name='user_role_enum'),
               type_=sa.Enum('EDITOR', 'TRUSTED_EDITOR', 'MODERATOR', 'ADMIN', name='userrole', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'EDITOR'::user_role_enum"))
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_google_id', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert database schema changes.
    
    WARNING: Make sure this migration is reversible!
    Consider data loss implications before rolling back.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_google_id', 'users', ['google_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('EDITOR', 'TRUSTED_EDITOR', 'MODERATOR', 'ADMIN', name='userrole', native_enum=False),
               type_=postgresql.ENUM('EDITOR', 'TRUSTED_EDITOR', 'MODERATOR', 'ADMIN', name='user_role_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'EDITOR'::user_role_enum"))
    op.create_index('idx_team_sponsor_link_era_id', 'team_sponsor_link', ['era_id'], unique=False)
    op.create_index('idx_team_sponsor_link_brand_id', 'team_sponsor_link', ['brand_id'], unique=False)
    op.create_index('idx_team_node_legal_name', 'team_node', ['legal_name'], unique=False)
    op.create_index('idx_team_node_is_active', 'team_node', ['is_active'], unique=False)
    op.create_index('idx_team_node_founding_year', 'team_node', ['founding_year'], unique=False)
    op.create_index('idx_team_node_dissolution_year', 'team_node', ['dissolution_year'], unique=False)
    op.create_index('idx_team_era_tier_level', 'team_era', ['tier_level'], unique=False)
    op.create_index('idx_team_era_season_year', 'team_era', ['season_year'], unique=False)
    op.create_index('idx_team_era_node_id', 'team_era', ['node_id'], unique=False)
    op.drop_column('team_era', 'country_code')
    op.create_index('idx_sponsor_master_protected', 'sponsor_master', ['is_protected'], unique=False)
    op.create_index('idx_sponsor_master_legal_name', 'sponsor_master', ['legal_name'], unique=False)
    op.create_index('idx_sponsor_brand_master_id', 'sponsor_brand', ['master_id'], unique=False)
    op.create_index('idx_lineage_event_year', 'lineage_event', ['event_year'], unique=False)
    op.create_index('idx_lineage_event_type', 'lineage_event', ['event_type'], unique=False)
    op.create_index('idx_lineage_event_successor', 'lineage_event', ['successor_node_id'], unique=False)
    op.create_index('idx_lineage_event_predecessor', 'lineage_event', ['predecessor_node_id'], unique=False)
    op.alter_column('lineage_event', 'event_type',
               existing_type=sa.Enum('LEGAL_TRANSFER', 'SPIRITUAL_SUCCESSION', 'MERGE', 'SPLIT', name='event_type_enum', native_enum=False),
               type_=postgresql.ENUM('LEGAL_TRANSFER', 'SPIRITUAL_SUCCESSION', 'MERGE', 'SPLIT', name='lineage_event_type_enum'),
               existing_nullable=False)
    op.create_index('idx_edit_history_user_id', 'edit_history', ['user_id'], unique=False)
    op.create_index('idx_edit_history_status', 'edit_history', ['status'], unique=False)
    op.create_index('idx_edit_history_entity', 'edit_history', ['entity_type', 'entity_id'], unique=False)
    op.alter_column('edit_history', 'snapshot_after',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('edit_history', 'snapshot_before',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('edit_history', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'APPLIED', name='editstatus', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'APPLIED', name='edit_status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::edit_status_enum"))
    op.alter_column('edit_history', 'action',
               existing_type=sa.Enum('CREATE', 'UPDATE', 'DELETE', name='editaction', native_enum=False),
               type_=postgresql.ENUM('CREATE', 'UPDATE', 'DELETE', name='edit_action_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
