"""make_user_refs_nullable

Revision ID: d8243ac55282
Revises: 71801b75caaa
Create Date: 2026-01-11 23:38:05.262332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8243ac55282'
down_revision: Union[str, None] = '71801b75caaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply database schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert database schema changes.
    
    WARNING: Make sure this migration is reversible!
    Consider data loss implications before rolling back.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
