"""add_is_stale_to_precomputed_layouts

Revision ID: d9ba2b5615d2
Revises: 990f5be30082
Create Date: 2026-02-05 17:53:53.377493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9ba2b5615d2'
down_revision: Union[str, None] = '990f5be30082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply database schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('precomputed_layouts', sa.Column('is_stale', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('precomputed_layouts', 'optimized_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('idx_family_hash', table_name='precomputed_layouts')
    op.drop_index('idx_optimized_at', table_name='precomputed_layouts')
    op.create_unique_constraint(None, 'precomputed_layouts', ['family_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert database schema changes.
    
    WARNING: Make sure this migration is reversible!
    Consider data loss implications before rolling back.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'precomputed_layouts', type_='unique')
    op.create_index('idx_optimized_at', 'precomputed_layouts', ['optimized_at'], unique=False)
    op.create_index('idx_family_hash', 'precomputed_layouts', ['family_hash'], unique=False)
    op.alter_column('precomputed_layouts', 'optimized_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('precomputed_layouts', 'is_stale')
    # ### end Alembic commands ###
