"""add unique constraint to lineage links

Revision ID: e2a35d1722cb
Revises: d9ba2b5615d2
Create Date: 2026-02-07 16:57:24.494996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a35d1722cb'
down_revision: Union[str, None] = 'd9ba2b5615d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply database schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_lineage_link', 'lineage_event', ['predecessor_node_id', 'successor_node_id', 'event_year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert database schema changes.
    
    WARNING: Make sure this migration is reversible!
    Consider data loss implications before rolling back.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_lineage_link', 'lineage_event', type_='unique')
    # ### end Alembic commands ###
