"""add_is_protected_to_team_era

Revision ID: efc94c85dbe0
Revises: d0d769119ce5
Create Date: 2025-12-22 18:10:57.244579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc94c85dbe0'
down_revision: Union[str, None] = 'd0d769119ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply database schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsor_brand', sa.Column('is_protected', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('team_era', sa.Column('is_protected', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert database schema changes.
    
    WARNING: Make sure this migration is reversible!
    Consider data loss implications before rolling back.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_era', 'is_protected')
    op.drop_column('sponsor_brand', 'is_protected')
    # ### end Alembic commands ###
