export const IOC_CODES = [
    { code: 'AFG', name: 'Afghanistan', iso2: 'af' },
    { code: 'ALB', name: 'Albania', iso2: 'al' },
    { code: 'ALG', name: 'Algeria', iso2: 'dz' },
    { code: 'AND', name: 'Andorra', iso2: 'ad' },
    { code: 'ANG', name: 'Angola', iso2: 'ao' },
    { code: 'ARG', name: 'Argentina', iso2: 'ar' },
    { code: 'ARM', name: 'Armenia', iso2: 'am' },
    { code: 'ARU', name: 'Aruba', iso2: 'aw' },
    { code: 'ASA', name: 'American Samoa', iso2: 'as' },
    { code: 'AUS', name: 'Australia', iso2: 'au' },
    { code: 'AUT', name: 'Austria', iso2: 'at' },
    { code: 'AZE', name: 'Azerbaijan', iso2: 'az' },
    { code: 'BAH', name: 'Bahamas', iso2: 'bs' },
    { code: 'BAN', name: 'Bangladesh', iso2: 'bd' },
    { code: 'BAR', name: 'Barbados', iso2: 'bb' },
    { code: 'BDI', name: 'Burundi', iso2: 'bi' },
    { code: 'BEL', name: 'Belgium', iso2: 'be' },
    { code: 'BEN', name: 'Benin', iso2: 'bj' },
    { code: 'BER', name: 'Bermuda', iso2: 'bm' },
    { code: 'BHU', name: 'Bhutan', iso2: 'bt' },
    { code: 'BIH', name: 'Bosnia and Herzegovina', iso2: 'ba' },
    { code: 'BIZ', name: 'Belize', iso2: 'bz' },
    { code: 'BLR', name: 'Belarus', iso2: 'by' },
    { code: 'BOL', name: 'Bolivia', iso2: 'bo' },
    { code: 'BOT', name: 'Botswana', iso2: 'bw' },
    { code: 'BRA', name: 'Brazil', iso2: 'br' },
    { code: 'BRN', name: 'Bahrain', iso2: 'bh' },
    { code: 'BRU', name: 'Brunei', iso2: 'bn' },
    { code: 'BUL', name: 'Bulgaria', iso2: 'bg' },
    { code: 'BUR', name: 'Burkina Faso', iso2: 'bf' },
    { code: 'CAF', name: 'Central African Republic', iso2: 'cf' },
    { code: 'CAM', name: 'Cambodia', iso2: 'kh' },
    { code: 'CAN', name: 'Canada', iso2: 'ca' },
    { code: 'CAY', name: 'Cayman Islands', iso2: 'ky' },
    { code: 'CGO', name: 'Congo', iso2: 'cg' },
    { code: 'CHA', name: 'Chad', iso2: 'td' },
    { code: 'CHI', name: 'Chile', iso2: 'cl' },
    { code: 'CHN', name: 'China', iso2: 'cn' },
    { code: 'CIV', name: 'Côte d\'Ivoire', iso2: 'ci' },
    { code: 'CMR', name: 'Cameroon', iso2: 'cm' },
    { code: 'COD', name: 'DR Congo', iso2: 'cd' },
    { code: 'COK', name: 'Cook Islands', iso2: 'ck' },
    { code: 'COL', name: 'Colombia', iso2: 'co' },
    { code: 'COM', name: 'Comoros', iso2: 'km' },
    { code: 'CPV', name: 'Cape Verde', iso2: 'cv' },
    { code: 'CRC', name: 'Costa Rica', iso2: 'cr' },
    { code: 'CRO', name: 'Croatia', iso2: 'hr' },
    { code: 'CUB', name: 'Cuba', iso2: 'cu' },
    { code: 'CYP', name: 'Cyprus', iso2: 'cy' },
    { code: 'CZE', name: 'Czech Republic', iso2: 'cz' },
    { code: 'DEN', name: 'Denmark', iso2: 'dk' },
    { code: 'DJI', name: 'Djibouti', iso2: 'dj' },
    { code: 'DMA', name: 'Dominica', iso2: 'dm' },
    { code: 'DOM', name: 'Dominican Republic', iso2: 'do' },
    { code: 'ECU', name: 'Ecuador', iso2: 'ec' },
    { code: 'EGY', name: 'Egypt', iso2: 'eg' },
    { code: 'ERI', name: 'Eritrea', iso2: 'er' },
    { code: 'ESA', name: 'El Salvador', iso2: 'sv' },
    { code: 'ESP', name: 'Spain', iso2: 'es' },
    { code: 'EST', name: 'Estonia', iso2: 'ee' },
    { code: 'ETH', name: 'Ethiopia', iso2: 'et' },
    { code: 'FIJ', name: 'Fiji', iso2: 'fj' },
    { code: 'FIN', name: 'Finland', iso2: 'fi' },
    { code: 'FRA', name: 'France', iso2: 'fr' },
    { code: 'FSM', name: 'Federated States of Micronesia', iso2: 'fm' },
    { code: 'GAB', name: 'Gabon', iso2: 'ga' },
    { code: 'GAM', name: 'Gambia', iso2: 'gm' },
    { code: 'GBR', name: 'Great Britain', iso2: 'gb' },
    { code: 'GBS', name: 'Guinea-Bissau', iso2: 'gw' },
    { code: 'GEO', name: 'Georgia', iso2: 'ge' },
    { code: 'GEQ', name: 'Equatorial Guinea', iso2: 'gq' },
    { code: 'GER', name: 'Germany', iso2: 'de' },
    { code: 'GHA', name: 'Ghana', iso2: 'gh' },
    { code: 'GRE', name: 'Greece', iso2: 'gr' },
    { code: 'GRN', name: 'Grenada', iso2: 'gd' },
    { code: 'GUA', name: 'Guatemala', iso2: 'gt' },
    { code: 'GUI', name: 'Guinea', iso2: 'gn' },
    { code: 'GUM', name: 'Guam', iso2: 'gu' },
    { code: 'GUY', name: 'Guyana', iso2: 'gy' },
    { code: 'HAI', name: 'Haiti', iso2: 'ht' },
    { code: 'HKG', name: 'Hong Kong', iso2: 'hk' },
    { code: 'HON', name: 'Honduras', iso2: 'hn' },
    { code: 'HUN', name: 'Hungary', iso2: 'hu' },
    { code: 'INA', name: 'Indonesia', iso2: 'id' },
    { code: 'IND', name: 'India', iso2: 'in' },
    { code: 'IRI', name: 'Iran', iso2: 'ir' },
    { code: 'IRL', name: 'Ireland', iso2: 'ie' },
    { code: 'IRQ', name: 'Iraq', iso2: 'iq' },
    { code: 'ISL', name: 'Iceland', iso2: 'is' },
    { code: 'ISR', name: 'Israel', iso2: 'il' },
    { code: 'ISV', name: 'Virgin Islands', iso2: 'vi' },
    { code: 'ITA', name: 'Italy', iso2: 'it' },
    { code: 'IVB', name: 'British Virgin Islands', iso2: 'vg' },
    { code: 'JAM', name: 'Jamaica', iso2: 'jm' },
    { code: 'JOR', name: 'Jordan', iso2: 'jo' },
    { code: 'JPN', name: 'Japan', iso2: 'jp' },
    { code: 'KAZ', name: 'Kazakhstan', iso2: 'kz' },
    { code: 'KEN', name: 'Kenya', iso2: 'ke' },
    { code: 'KGZ', name: 'Kyrgyzstan', iso2: 'kg' },
    { code: 'KIR', name: 'Kiribati', iso2: 'ki' },
    { code: 'KOR', name: 'South Korea', iso2: 'kr' },
    { code: 'KOS', name: 'Kosovo', iso2: 'xk' },
    { code: 'KSA', name: 'Saudi Arabia', iso2: 'sa' },
    { code: 'KUW', name: 'Kuwait', iso2: 'kw' },
    { code: 'LAO', name: 'Laos', iso2: 'la' },
    { code: 'LAT', name: 'Latvia', iso2: 'lv' },
    { code: 'LBA', name: 'Libya', iso2: 'ly' },
    { code: 'LBN', name: 'Lebanon', iso2: 'lb' },
    { code: 'LBR', name: 'Liberia', iso2: 'lr' },
    { code: 'LCA', name: 'Saint Lucia', iso2: 'lc' },
    { code: 'LES', name: 'Lesotho', iso2: 'ls' },
    { code: 'LIE', name: 'Liechtenstein', iso2: 'li' },
    { code: 'LTU', name: 'Lithuania', iso2: 'lt' },
    { code: 'LUX', name: 'Luxembourg', iso2: 'lu' },
    { code: 'MAD', name: 'Madagascar', iso2: 'mg' },
    { code: 'MAR', name: 'Morocco', iso2: 'ma' },
    { code: 'MAS', name: 'Malaysia', iso2: 'my' },
    { code: 'MAW', name: 'Malawi', iso2: 'mw' },
    { code: 'MDA', name: 'Moldova', iso2: 'md' },
    { code: 'MDV', name: 'Maldives', iso2: 'mv' },
    { code: 'MEX', name: 'Mexico', iso2: 'mx' },
    { code: 'MGL', name: 'Mongolia', iso2: 'mn' },
    { code: 'MHL', name: 'Marshall Islands', iso2: 'mh' },
    { code: 'MKD', name: 'North Macedonia', iso2: 'mk' },
    { code: 'MLI', name: 'Mali', iso2: 'ml' },
    { code: 'MLT', name: 'Malta', iso2: 'mt' },
    { code: 'MNE', name: 'Montenegro', iso2: 'me' },
    { code: 'MON', name: 'Monaco', iso2: 'mc' },
    { code: 'MOZ', name: 'Mozambique', iso2: 'mz' },
    { code: 'MRI', name: 'Mauritius', iso2: 'mu' },
    { code: 'MTN', name: 'Mauritania', iso2: 'mr' },
    { code: 'MYA', name: 'Myanmar', iso2: 'mm' },
    { code: 'NAM', name: 'Namibia', iso2: 'na' },
    { code: 'NCA', name: 'Nicaragua', iso2: 'ni' },
    { code: 'NED', name: 'Netherlands', iso2: 'nl' },
    { code: 'NEP', name: 'Nepal', iso2: 'np' },
    { code: 'NER', name: 'Niger', iso2: 'ne' },
    { code: 'NGR', name: 'Nigeria', iso2: 'ng' },
    { code: 'NOR', name: 'Norway', iso2: 'no' },
    { code: 'NRU', name: 'Nauru', iso2: 'nr' },
    { code: 'NZL', name: 'New Zealand', iso2: 'nz' },
    { code: 'OMA', name: 'Oman', iso2: 'om' },
    { code: 'PAK', name: 'Pakistan', iso2: 'pk' },
    { code: 'PAN', name: 'Panama', iso2: 'pa' },
    { code: 'PAR', name: 'Paraguay', iso2: 'py' },
    { code: 'PER', name: 'Peru', iso2: 'pe' },
    { code: 'PHI', name: 'Philippines', iso2: 'ph' },
    { code: 'PLE', name: 'Palestine', iso2: 'ps' },
    { code: 'PLW', name: 'Palau', iso2: 'pw' },
    { code: 'PNG', name: 'Papua New Guinea', iso2: 'pg' },
    { code: 'POL', name: 'Poland', iso2: 'pl' },
    { code: 'POR', name: 'Portugal', iso2: 'pt' },
    { code: 'PRK', name: 'North Korea', iso2: 'kp' },
    { code: 'PUR', name: 'Puerto Rico', iso2: 'pr' },
    { code: 'QAT', name: 'Qatar', iso2: 'qa' },
    { code: 'ROU', name: 'Romania', iso2: 'ro' },
    { code: 'RSA', name: 'South Africa', iso2: 'za' },
    { code: 'RUS', name: 'Russia', iso2: 'ru' },
    { code: 'RWA', name: 'Rwanda', iso2: 'rw' },
    { code: 'SAM', name: 'Samoa', iso2: 'ws' },
    { code: 'SEN', name: 'Senegal', iso2: 'sn' },
    { code: 'SEY', name: 'Seychelles', iso2: 'sc' },
    { code: 'SGP', name: 'Singapore', iso2: 'sg' },
    { code: 'SKN', name: 'Saint Kitts and Nevis', iso2: 'kn' },
    { code: 'SLE', name: 'Sierra Leone', iso2: 'sl' },
    { code: 'SLO', name: 'Slovenia', iso2: 'si' },
    { code: 'SMR', name: 'San Marino', iso2: 'sm' },
    { code: 'SOL', name: 'Solomon Islands', iso2: 'sb' },
    { code: 'SOM', name: 'Somalia', iso2: 'so' },
    { code: 'SRB', name: 'Serbia', iso2: 'rs' },
    { code: 'SRI', name: 'Sri Lanka', iso2: 'lk' },
    { code: 'SSD', name: 'South Sudan', iso2: 'ss' },
    { code: 'STP', name: 'Sao Tome and Principe', iso2: 'st' },
    { code: 'SUD', name: 'Sudan', iso2: 'sd' },
    { code: 'SUI', name: 'Switzerland', iso2: 'ch' },
    { code: 'SUR', name: 'Suriname', iso2: 'sr' },
    { code: 'SVK', name: 'Slovakia', iso2: 'sk' },
    { code: 'SWE', name: 'Sweden', iso2: 'se' },
    { code: 'SWZ', name: 'Eswatini', iso2: 'sz' },
    { code: 'SYR', name: 'Syria', iso2: 'sy' },
    { code: 'TAN', name: 'Tanzania', iso2: 'tz' },
    { code: 'TGA', name: 'Tonga', iso2: 'to' },
    { code: 'THA', name: 'Thailand', iso2: 'th' },
    { code: 'TJK', name: 'Tajikistan', iso2: 'tj' },
    { code: 'TKM', name: 'Turkmenistan', iso2: 'tm' },
    { code: 'TLS', name: 'Timor-Leste', iso2: 'tl' },
    { code: 'TOG', name: 'Togo', iso2: 'tg' },
    { code: 'TPE', name: 'Chinese Taipei', iso2: 'tw' },
    { code: 'TTO', name: 'Trinidad and Tobago', iso2: 'tt' },
    { code: 'TUN', name: 'Tunisia', iso2: 'tn' },
    { code: 'TUR', name: 'Turkey', iso2: 'tr' },
    { code: 'TUV', name: 'Tuvalu', iso2: 'tv' },
    { code: 'UAE', name: 'United Arab Emirates', iso2: 'ae' },
    { code: 'UGA', name: 'Uganda', iso2: 'ug' },
    { code: 'UKR', name: 'Ukraine', iso2: 'ua' },
    { code: 'URU', name: 'Uruguay', iso2: 'uy' },
    { code: 'USA', name: 'United States', iso2: 'us' },
    { code: 'UZB', name: 'Uzbekistan', iso2: 'uz' },
    { code: 'VAN', name: 'Vanuatu', iso2: 'vu' },
    { code: 'VEN', name: 'Venezuela', iso2: 've' },
    { code: 'VIE', name: 'Vietnam', iso2: 'vn' },
    { code: 'VIN', name: 'Saint Vincent and the Grenadines', iso2: 'vc' },
    { code: 'YEM', name: 'Yemen', iso2: 'ye' },
    { code: 'ZAM', name: 'Zambia', iso2: 'zm' },
    { code: 'ZIM', name: 'Zimbabwe', iso2: 'zw' }
];

export const getCountryName = (code) => {
    const found = IOC_CODES.find(c => c.code === code);
    return found ? found.name : code;
};

/**
 * Returns the Alpha-2 code for a given 3-letter IOC code.
 * Returns null if not found.
 */
export const getCountryFlag = (iocCode) => {
    if (!iocCode) return null;
    const found = IOC_CODES.find(c => c.code === iocCode.toUpperCase());
    return found ? found.iso2 : null;
};
